{"name": "Проверяем, что нельзя создать пользователя, если такой уже зарегистрирован", "status": "passed", "start": 1731119430033, "stop": 1731119430795, "uuid": "5636fcf5-222d-47dc-b9ab-aff188ceec4b", "historyId": "3e800a99313069f52b11a954db1ce0d3", "testCaseId": "3e800a99313069f52b11a954db1ce0d3", "fullName": "tests.test_create_user.TestCreateUser#test_cannot_create_existing_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-0KFG2SR"}, {"name": "thread", "value": "12036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}