{"name": "Проверяем, что нельзя создать заказ с некорректным значением ингредиентов", "status": "passed", "start": 1731119428534, "stop": 1731119428646, "uuid": "e2e8715c-40d2-4fb1-a697-9d0b0e2ac8a5", "historyId": "e0c42f981a740413db19bec91d5db09e", "testCaseId": "e0c42f981a740413db19bec91d5db09e", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_invalid_ingredients_returns_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-0KFG2SR"}, {"name": "thread", "value": "12036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}