{"name": "Проверяем логин под данными существующего пользователя", "status": "passed", "start": 1731119433358, "stop": 1731119434866, "uuid": "abdf339c-050c-483d-bde3-3fcfeab681f8", "historyId": "8d3e3580b83ce1561996445524a8ca03", "testCaseId": "8d3e3580b83ce1561996445524a8ca03", "fullName": "tests.test_user_login.TestUserLogin#test_login_valid_user_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-0KFG2SR"}, {"name": "thread", "value": "12036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}